### ISSUE TITLE
Cannot register CPU DAI

### ISSUE THREAD

**Issue by cygnusnow** [MicrosemiVoiceProcessing/ZLK38AVS#2]
Hi,

I have complied the code on raspberry Pi3. But after I install all the libraries and apps to raspberry PI3. I got some error message from "dmesg". And aplay and arecord cannot play and capture the audio data.  Can some one help me to fix this issue?
[    2.149832] snd_microsemi_dac_probe :85 HERE...
[    2.149878] snd-microsemi-dac soc:sound: ASoC: CPU DAI (null) not registered
[    2.150101] snd_microsemi_dac_probe :105 HERE...
[    2.150114] snd-microsemi-dac soc:sound: snd_soc_register_card() failed: -517
[    2.396070] systemd-udevd[138]: starting version 215
[    2.791449] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    2.791667] snd_microsemi_dac_probe :85 HERE...
[    2.791705] snd-microsemi-dac soc:sound: ASoC: CPU DAI (null) not registered
[    2.791715] snd_microsemi_dac_probe :105 HERE...
[    2.791727] snd-microsemi-dac soc:sound: snd_soc_register_card() failed: -517
[    2.804996] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    2.805228] snd_microsemi_dac_probe :85 HERE...
[    2.805272] snd-microsemi-dac soc:sound: ASoC: CPU DAI (null) not registered
[    2.805282] snd_microsemi_dac_probe :105 HERE...
[    2.805295] snd-microsemi-dac soc:sound: snd_soc_register_card() failed: -517
[    2.806962] snd_microsemi_dac_probe :85 HERE...
[    2.813948] snd-microsemi-dac soc:sound: zl380xx-dai <-> 3f203000.i2s mapping ok

**Comment by bonyjean1** [comment]
Hi,
That's not an issue. During the power up process the ALSA sound drivers will be loaded sequentially:
- the Broadcom platform driver:
- the ALSA machine driver: snd-soc-microsemi-dac
- the codec driver: snd-soc-zl380xx

While the machine drive is awaiting for the codec driver to be loaded then you may received an error snd_soc_register_card() failed: -517. But this error will go away once all the drivers in the sequence above are loaded.

As you can see per the last line in your log, the driver was finally registered properly once all drivers were loaded,
[ 2.813948] snd-microsemi-dac soc:sound: zl380xx-dai <-> 3f203000.i2s mapping ok

Best regards,
Jean

**Comment by bonyjean1** [comment]
Once your Pi3 is fully booted, you can confirm that the sound device is properly registered by issuing  from a terminal 
aplay -l

That should display The Microsemi sound device

**Comment by cygnusnow** [comment]
@bonyjean1  You are right.   Thanks.
